// <auto-generated />
namespace QLNS.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initTableTD_CauHinhSangLocUngVien : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initTableTD_CauHinhSangLocUngVien));
        
        string IMigrationMetadata.Id
        {
            get { return "201905041110203_initTableTD_CauHinhSangLocUngVien"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
